# 1. Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-demo

---

# 2. NGINX Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: krytox/webapp:v7
          ports:
            - containerPort: 80

---

# 3. NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-demo
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Optional; Kubernetes will auto-assign if omitted
